aluno/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.aluno, name='aluno'),
    path('administrador/', views.administrador, name='administrador'),
    path('alunos/', views.lista_alunos, name='aluno_alunos'),
    path('alunos-novo', views.aluno_novo, name='aluno_aluno_novo'),
    path('alunos-update/<int:id>', views.aluno_update, name='aluno_aluno_update'),
    path('alunos-delete/<int:id>', views.aluno_delete, name='aluno_aluno_delete'),
    path('users/<int:user_id>/edit/', views.edit_user, name='edit_user'),
    path('minhaconta/', views.minhaconta, name='minhaconta'),

    path('curso/', views.lista_cursos, name='lista_cursos'),
    path('cursonovo/', views.curso_novo, name='curso_novo'),
    path('curso-update/<int:id>', views.curso_update, name='curso_update'),
    path('curso-delete/<int:id>', views.curso_delete, name='curso_delete'),
    path('curso/<int:id>', views.curso_detalhe, name='curso_detalhe'),
    path('curso/changestatus/<int:id>/<int:categoria_licao>/', views.changeStatus, name='change_status'),
    path('curso/<int:curso_id>/licao/novo/', views.licao_novo, name='licao_novo'),

    path('inscricao/', views.lista_inscricoes, name='lista_inscricoes'),
    path('inscricaolista/', views.lista_inscricao, name='lista_inscricao'),
    path('inscricaonovo/', views.inscricao_novo, name='inscricao_novo'),
    path('inscricao-update/<int:id>', views.inscricao_update, name='inscricao_update'),
    path('inscricao-delete/<int:id>', views.inscricao_delete, name='inscricao_delete'),

    path('licao/<int:id>/', views.lista_Licao, name='lista_licao'),
    path('licao-lista/<int:id>', views.licao_detalhe, name='licao_detalhe'),
    path('licao-update/<int:id>', views.licao_update, name='licao_update'),
    path('licao-delete/<int:id>', views.licao_delete, name='licao_delete'),
    path('download/<int:licao_id>/', views.download_licao, name='download_licao'),

    path('digitacao/', views.lista_digitacao, name='lista_digitacao'),
    path('digitacao-novo/', views.digitacao_novo, name='digitacao_novo'),
    path('digitacao-update/<int:id>', views.digitacao_update, name='digitacao_update'),
    path('digitacao-delete/<int:id>', views.digitacao_delete, name='digitacao_delete'),

    path('inscricao-digitacao/', views.lista_inscricaodigitacao, name='lista_inscricaodigitacao'),
    path('inscricao-digitacao-novo/', views.inscricaodigitacao_novo, name='inscricaodigitacao_novo'),
    path('inscricao-digitacao-update/<int:id>', views.inscricaodigitacao_update, name='inscricaodigitacao_update'),
    path('inscricao-digitacao-delete/<int:id>', views.inscricaodigitacao_delete, name='inscricaodigitacao_delete'),

    path('cursodigitacao/<int:id>', views.cursodigitacao_detalhe, name='cursodigitacao_detalhe'),
    path('cursodigitacao/next/<int:id>', views.cursodigitacao_next, name='cursodigitacao_next'),
    path('cursodigitacao/relatorioDigitacao/', views.relatorioDigitacao, name='relatorioDigitacao'),
    path('cursodigitacao/relatorioDigitacao/relatorio', views.obter_relatorioDigitacao, name='obter_relatorioDigitacao'),
    path('rankindigitacao/', views.rankindigitacao, name='rankindigitacao'),

    path('provasdigitacao/<int:id>', views.provasdigitacao, name='provasdigitacao'),
    path('provasdigitacao/prova/', views.criar_prova_digitacao, name='criar_prova_digitacao'),  
    path('prova/<int:curso_id>/', views.prova, name='prova'),
    path('processar-respostas/<int:curso_id>/', views.processar_respostas, name='processar_respostas'),
    path('resultado-prova/<int:curso_id>/', views.resultado_prova, name='resultado_prova'),
    path('prova/questoes/<int:id>', views.questoes_detalhe, name='questoes_detalhe'),

    path('itens_detalhe/<int:curso_id>/<int:questao_id>', views.itens_detalhe, name='itens_detalhe'),
    path('item/delete/<int:item_id>', views.excluir_item, name='excluir_item'),
    path('item/editar/<int:item_id>', views.editar_item, name='editar_item'),
    path('questao/criar/<int:curso_id>/', views.criar_questao, name='criar_questao'),
    path('questao/editar/<int:questao_id>', views.editar_questao, name='editar_questao'),
    path('questao/delete/<int:questao_id>', views.excluir_questao, name='excluir_questao'),
    
    path('curso/certificado/<int:curso_id>/', views.gerar_certificado, name='gerar_certificado'),
    path('curso/certificado/teste/<int:curso_id>/', views.certificadoteste, name='certificadoteste'),
    path('curso/certificado/gerar_pdf/<int:curso_id>/', views.render_pdf_view, name='render_pdf_view'),
    path('curso/certificado/gerar_pdfDig/', views.render_pdf_digitacao_view, name='render_pdf_digitacao_view'),

    path('marcar-tour-completo/', views.marcar_tour_completo, name='marcar_tour_completo'),
    path('toggle-tour-status/', views.toggle_tour_status, name='toggle_tour_status'),
    path('marcar-tour-completodigi/', views.marcar_tour_completoDig, name='marcar_tour_completoDig'),
    path('toggle-tour-status-dig/', views.toggle_tour_status_dig, name='toggle_tour_status_dig'),
]

infox/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aluno.urls')),
    path('', include('django.contrib.auth.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path("accounts/", include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('pedido/', include('pedido.urls')),
    path('perfil/', include('perfil.urls')),
    
    path('site/', views.site_detalhes, name='site_detalhes'),

    path('infox/<int:id>/', views.infox_detalhes, name='infox_detalhes'),
    path('infoxlista/<int:id>/', views.infox_lista, name='infox_lista'),
    path('infoxnovo/', views.infox_novo, name='infox_novo'),
    path('infoxupdate/<int:id>/', views.infox_update, name='infox_update'),
    path('infoxequinovo/', views.infox_equi_novo, name='infox_equi_novo'),
    path('infoxequilista/', views.infox_equi_lista, name='infox_equi_lista'),
    path('infoxequiupdate/<int:id>/', views.infox_equi_update, name='infox_equi_update'),
    path('infoxequidelete/<int:id>/', views.infox_equi_delete, name='infox_equi_delete'),

    path('contato/', views.contato_detalhes, name='contato_detalhes'),
    path('contatoenviado/', views.contato_enviado, name='contato_enviado'),
    
    path('superior/', views.superior_detalhes, name='superior_detalhes'),
    path('superiorlista/<int:id>/', views.superior_lista, name='superior_lista'),
    path('superiornovo/', views.superior_novo, name='superior_novo'),
    path('superiorupdate/<int:id>/', views.superior_update, name='superior_update'),
    path('superiorlogonovo/', views.superior_logo_novo, name='superior_logo_novo'),
    path('superiorlogolista', views.superior_logo_lista, name='superior_logo_lista'),
    path('superiorlogoupdate/<int:id>/', views.superior_logo_update, name='superior_logo_update'),
    path('superiorlogodelete/<int:id>/', views.superior_logo_delete, name='superior_logo_delete'),
    path('superiorsupernovo/', views.superior_super_novo, name='superior_super_novo'),
    path('superiorsuperlista/', views.superior_super_lista, name='superior_super_lista'),
    path('superiorsuperupdate/<int:id>/', views.superior_super_update, name='superior_super_update'),
    path('superiorsuperdelete/<int:id>/', views.superior_super_delete, name='superior_super_delete'),
    path('superiortecnovo/', views.superior_tec_novo, name='superior_tec_novo'),
    path('superiorteclista/', views.superior_tec_lista, name='superior_tec_lista'),
    path('superiortecupdate/<int:id>/', views.superior_tec_update, name='superior_tec_update'),
    path('superiortecdelete/<int:id>/', views.superior_tec_delete, name='superior_tec_delete'),
    path('superiorposnovo/', views.superior_pos_novo, name='superior_pos_novo'),
    path('superiorposlista/', views.superior_pos_lista, name='superior_pos_lista'),
    path('superiorposupdate/<int:id>/', views.superior_pos_update, name='superior_pos_update'),
    path('superiorposdelete/<int:id>/', views.superior_pos_delete, name='superior_pos_delete'),
    path('superiormbanovo/', views.superior_mba_novo, name='superior_mba_novo'),
    path('superiormbalista/', views.superior_mba_lista, name='superior_mba_lista'),
    path('superiormbaupdate/<int:id>/', views.superior_mba_update, name='superior_mba_update'),
    path('superiormbadelete/<int:id>/', views.superior_mba_delete, name='superior_mba_delete'),

    path('prof/', views.prof_detalhes, name='prof_detalhes'),
    path('profnovo/', views.prof_novo, name='prof_novo'),
    path('proflista/<int:id>/', views.prof_lista, name='prof_lista'),
    path('profupdate/<int:id>/', views.prof_update, name='prof_update'),
    path('proflogonovo/', views.prof_logo_novo, name='prof_logo_novo'),
    path('proflogolista', views.prof_logo_lista, name='prof_logo_lista'),
    path('proflogoupdate/<int:id>/', views.prof_logo_update, name='prof_logo_update'),
    path('proflogodelete/<int:id>/', views.prof_logo_delete, name='prof_logo_delete'),
    path('profpacotenovo/', views.prof_pacote_novo, name='prof_pacote_novo'),
    path('profpacotelista/', views.prof_pacote_lista, name='prof_pacote_lista'),
    path('profpacoteupdate/<int:id>/', views.prof_pacote_update, name='prof_pacote_update'),
    path('profpacotedelete/<int:id>/', views.prof_pacote_delete, name='prof_pacote_delete'),
    path('profcursonovo/', views.prof_curso_novo, name='prof_curso_novo'),
    path('profcursolista/', views.prof_curso_lista, name='prof_curso_lista'),
    path('profcursoupdate/<int:id>/', views.prof_curso_update, name='prof_curso_update'),
    path('profcursodelete/<int:id>/', views.prof_curso_delete, name='prof_curso_delete'),
    path('profturmanovo/', views.prof_turma_novo, name='prof_turma_novo'),
    path('profturmalista/', views.prof_turma_lista, name='prof_turma_lista'),
    path('profturmaupdate/<int:id>/', views.prof_turma_update, name='prof_turma_update'),
    path('profturmadelete/<int:id>/', views.prof_turma_delete, name='prof_turma_delete'),

    path('cursoson/', views.cursoson_detalhes, name='cursoson_detalhes'),
    path('cursosonindiv/<int:id>/', views.cursoson_indivi, name='cursoson_indivi'),
    path('cursosondig/', views.cursoson_dig, name='cursoson_dig'),
    
]

pedido/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pedido'

urlpatterns = [
    path('', views.Pagar, name='pagar'),
    path('carrinho/', views.Carrinho, name='carrinho'),
    path('addcarrinho/<int:id>/', views.AddCarrinho, name='addcarrinho'),
    path('addcarrinhodig/', views.AddCarrinhoDig, name='AddCarrinhoDig'),
    path('removercarrinho/<int:id>/', views.RemoverCarrinho, name='removercarrinho'),
    path('removercarrinhodig/', views.RemoverCarrinhoDig, name='removercarrinhodig'),
    path('continuarcarrinho/<int:id>/', views.ContinuarCarrinho, name='continuarcarrinho'),
    path('continuarcarrinhodig/', views.ContinuarCarrinhoDig, name='continuarcarrinhodig'),
    path('resumo/', views.Resumo, name='resumo'),
    
    #path('fecharpedido/', views.FecharPagar, name='fecharpagar'),
]

templates/base_login.html
{% load static %}
<!DOCTYPE html>
<html lang="br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'infox/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'infox/css/line-icons.css' %}">
    <link rel="stylesheet" href="{% static 'infox/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'infox/css/nivo-lightbox.css' %}">
    <link rel="stylesheet" href="{% static 'infox/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'infox/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'infox/css/infox.css' %}">
    <link rel="stylesheet" href="{% static 'infox/css/popup.css' %}">
    <link rel="stylesheet" href="{% static 'infox/css/responsive.css' %}">
    
    <link rel="icon" href="{% static '/media/logo_infox.ico' %}" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300&display=swap" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-46397689-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-46397689-2');
    </script>


    <title>Infox Polo Unfitec</title>
    <meta name="description" content="A Infox Polo Uniftec é uma escola diferenciada, aqui você econtra uma infinidade de cursos. Possuímos cursos bácisos, profissionalizantes, Robótica, LID, Projetista e muito mais... O nosso Ensino Superior contempla, Graduações, Pós-Graduações, MBA's e Técniocos! Estamos em São Marcos / RS há mais de 20 anos.">
    <meta name="keywords" content="Cursos, LID, Robótica, AutoCad, Graduação, MBA, Cursos Superiores, Pós-Graduação, Técnico, Informática, Escola">
    <meta name="author" content="Infox Polo Uniftec">
    <meta name="robots" content="index">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'media/logo_infox.ico' %}">
    

</head>
<body>
     
    {% block main %}
    {% endblock %}
    
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'infox/js/jquery-min.js' %} "></script>
    <script src="{% static 'infox/js/jquery.countdown.min.js' %} "></script>
    <script src="{% static 'infox/js/wow.js' %} "></script>
    <script src="{% static 'infox/js/jquery.slicknav.js' %} "></script>
    <script src="{% static 'infox/js/main.js' %} "></script>
    <script src="{% static 'infox/js/popup.js' %} "></script>
    <script src="https://kit.fontawesome.com/e27c3edd80.js" crossorigin="anonymous"></script>
        
</body>
</html>

templates/contato_detalhes.html
{% extends "base_login.html" %}
{% load static %}
{% block main %}
{% load custom_filters %}
{% load bootstrap %}

</head>
  
{% include 'nav.html' %}

<div class="gradCapa wow fadeInDown">
<div class="container">
<div class="row">
  <div class="col-sm-6 col-md-6 text-white align-self-center text-justify p-2">
    <br>
    <br>
    <br>
    <h1 class="wow animated bounce" data-wow-delay="0.2s">Se conecte com a gente</h1>
      <h5 class="wow bounceInDown" data-wow-delay="0.4s">Acompanhe nossas novidades.
        </h5>
        <div class="wow fadeInLeft" data-wow-delay="0.9s">

          <a href="https://wa.me/5554984346112"  class="me-4 text-reset" target="_blank">
            <i class="fab fa-whatsapp"></i>
          </a>
          <a href="https://www.facebook.com/infox.edu"  class="me-4 text-reset" target="_blank">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="https://www.instagram.com/infox.info/" class="me-4 text-reset" target="_blank">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="https://www.linkedin.com/company/infox-polo-uniftec" class="me-4 text-reset" target="_blank">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="https://www.youtube.com/user/cursosinfox" class="me-4 text-reset" target="_blank">
            <i class="fab fa-youtube"></i>
          </a>
        </div>
  </div>
  <div class="col">
    <div>
      <div class="text-primary wow fadeInDown" data-wow-delay="0.6s">
        <img class="d-block" src="{% static 'media/infox/infox_contato.png' %}" alt="Img_pessoa_Contato">
      </div>
    </div>     
  </div>
</div>
</div>
</div>



<!-- ======= Contact Section ======= -->
<section>
<div class="container" data-aos="fade-up">



  <div class="row p-5 text-secondary">

    <div class="col">

      <div class="row">
      <div class="col-2 align-self-center">
        <div class="">
          <span style="font-size: 3em; color: rgb(58, 58, 58);">
            <i class="fas fa-map-marker-alt"></i>
          </span>
        </div>
      </div>
      <div class="col">
        <div >
          <h5 class="text-secondary">Localização:</h5>
        </div>
        <div>
          <p>Avenida Venâncio Aires 1110, sala 11. Centro São Marcos</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-2 align-self-center">
        <div class="">
          <span style="font-size: 3em; color: rgb(58, 58, 58);">
            <i class="fas fa-envelope"></i>
          </span>
        </div>
      </div>
      <div class="col">
        <div >
          <h5 class="text-secondary">E-mail:</h5>
        </div>
        <div>
          <p>atendimento@cursosinfox.com.br</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-2 align-self-center">
        <div class="">
          <span style="font-size: 3em; color: rgb(58, 58, 58);">
            <i class="fab fa-whatsapp"></i>
          </span>
        </div>
      </div>
      <div class="col">
        <div >
          <h5 class="text-secondary">Telefone/whats:</h5>
        </div>
        <div>
          <p>54 98434-6112</p>
        </div>
      </div>
    </div>
  </div>

    <div class="col-lg-8 mt-5 mt-lg-0">

      <form method="POST" autocomplete="OFF">
        {% csrf_token %}
        
        <div class="row">
          <div class="col-md-6 form-group">
            <label for="{{ form.name.id_for_label }}">Nome:</label>
            {{ form.name }}
            {% if form.name.errors %}
                <div class="alert alert-danger">
                    {% for error in form.name.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
          </div>
          <div class="col-md-6 form-group mt-3 mt-md-0">
            <label for="{{ form.email.id_for_label }}">Email:</label>
            {{ form.email }}
            {% if form.email.errors %}
                <div class="alert alert-danger">
                    {% for error in form.email.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
          </div>
        </div>
        <div class="form-group">
            <label for="{{ form.subject.id_for_label }}">Assunto:</label>
            {{ form.subject }}
            {% if form.subject.errors %}
                <div class="alert alert-danger">
                    {% for error in form.subject.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        
        <!-- Campo Mensagem -->
        <div class="form-group">
            <label for="{{ form.message.id_for_label }}">Mensagem:</label>
            {{ form.message }}
            {% if form.message.errors %}
                <div class="alert alert-danger">
                    {% for error in form.message.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="text-end btn-sm" style="padding-top: 20px;">
          <input type="submit" value="Enviar" class="btn btn-primary mb-1" />
      </div>
    </form>
    </div>
  </div>
</div>
</section>

</body>

{% include 'footer.html' %}

{% endblock %}

templates/cursoson_dig.html
{% extends "base_login.html" %}
{% load static %}
{% block main %}
{% load bootstrap %}

</head>
  
{% include 'nav.html' %}
<style>
  .paineldiv {
  display:inline-block;
  width:300px;
  background-color: #f5f5f5;
  color: #000;
  font-size: 20px;
  vertical-align: middle;
  border-radius: 1px 1px 1px 1px;
  margin-top: -100px; /* Ajuste este valor conforme necessário */
}
.paineldivconteudo {
  display: inline-flex;
  background-color: #f5f5f5;
  color: #000;
  font-size: 20px;
  vertical-align: top;
  border-radius: 1px 1px 1px 1px;
  margin-top: 20px; /* Ajuste este valor conforme necessário */

}
.fixed-width {
    width: 320px;
  }

  .card-img-top{
  border-top-right-radius: 1px;
  border-top-left-radius: 1px;
  }
.iframe-container {
  position: relative;
  width: 100%;
  padding-top: 56.25%; /* 16:9 aspect ratio */
  overflow: hidden;
}
.iframe-container iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 0;
}
.thead-dark th {
  border-bottom: 2px solid;
}
thead th {
  border-bottom: 2px solid;
}
</style>

<div class="gradCapa wow fadeInDown">
    <div class="container" style="padding-top: 190px;">
    </div>
  </div>
</div>
<div class="container">
<div class="row justify-content-center">
<div class="col-12 col-md-3 fixed-width">
  <div class="card mb-3 paineldiv wow fadeInDown" data-wow-delay="0.1s">

    <img src="{% static 'media/curso/capa/digitacao.png' %}" class="card-img-top" alt="Capa curso dig">
      <div class="card-body">
        

        <h4 class="card-title text-primary">Digitação</h4>

        
        <p class="card-text">Aqui vai o detalhe do curso de digitação</p>
        <div class="d-flex justify-content-between">

          <p><i class="fa-regular fa-clock" style="color: purple; padding-right: 5px;"></i> {{ dig.horas }} horas</p>
          <p><i class="fa-solid fa-bookmark" style="color: purple; padding-right: 5px;"></i> {{ dig.licoes }} lições</p>
        </div>
        <p><i class="fa-solid fa-award" style="color: purple; padding-right: 5px;"></i> Certificado</p>
        <h4 class="text-center align-middle text-primary">R$ {{ dig.valor }}</h4>


        <div class="d-flex justify-content-center">
          <a href="{% url 'pedido:AddCarrinhoDig' %}">
            <button type="button" class="btn btn-primary" style="margin-top: 10px; height: 45px;">
              <i class="fa-solid fa-cart-shopping"></i> Add ao carrinho
            </button>
          </a>
      </div>

      </div>
    </div>
  </div>
    <div class="col-12 col-md" style="padding-top: 20px;">
    <div class="card mb-3 wow fadeInDown iframe-container">
      <iframe width="100%" height="100%" src="https://www.youtube.com/embed/VdLOQ5eNGMk" title="Muito prazer, chegou o Novo T-Cross | VW Brasil" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
    <h1 class="text-primary">Sobre o curso</h1>
    <div class="card mb-3 wow fadeInDown text-secondary">
      <div style="padding: 10px;">
        <section>
          <p>
            Seja bem-vindo(a) ao <strong>Curso de Digitação Online</strong>, uma plataforma completa para você aprender a digitar com eficiência e precisão. Desenvolvido para todos os níveis, do iniciante ao avançado, o curso é ideal tanto para quem deseja aprender a digitar do zero quanto para quem quer aprimorar sua velocidade e técnica.
          </p>
        
          <h5 class="text-primary">O que você vai aprender?</h5>
            <p><strong>Postura correta ao digitar:</strong> Evite dores e lesões com dicas essenciais sobre ergonomia e a posição adequada do corpo e das mãos ao teclado.</p>
            <p><strong>Posicionamento das mãos no teclado:</strong> Domine a linha inicial e as demais teclas, aprendendo a colocar seus dedos de forma correta e eficiente.</p>
            <p><strong>Velocidade e precisão:</strong> Através de 266 lições práticas e graduais, você aumentará sua velocidade de digitação, ao mesmo tempo em que reduz os erros.</p>
            <p><strong>Uso de símbolos e números:</strong> Além das letras, você aprenderá a digitar rapidamente números e símbolos especiais, essenciais no dia a dia.</p>

        
            <h5 class="text-primary">Funcionalidades exclusivas:</h5>
            <p><strong>Relatórios detalhados:</strong> Ao final de cada lição, você receberá um relatório com o seu desempenho, incluindo a velocidade de digitação (palavras por minuto) e a taxa de erros. Acompanhe sua evolução dia após dia!</p>
            <p><strong>Metas diárias:</strong> Defina seus próprios objetivos de prática e acompanhe sua progressão com o sistema de metas diárias.</p>
            <p><strong>Ranking e competição:</strong> Compita de maneira saudável com outros alunos. Desafie a si mesmo e veja sua posição no ranking geral.</p>
            <p><strong>Avaliações regulares:</strong> No final do curso teremos uma avaliação que medem seu progresso e oferecem feedback personalizado para que você possa aprimorar ainda mais suas habilidades.</p>
            <p><strong>Conquistas:</strong> E ainda desbloquei conquistas ao passar suas lições.</p>
          <h5 class="text-primary">Por que aprender a digitar?</h5>
          <p>
            A digitação rápida e precisa é uma habilidade fundamental no mercado de trabalho atual. Seja para estudantes, profissionais de todas as áreas ou simplesmente para quem deseja aumentar sua produtividade no uso diário do computador, este curso oferece a base necessária para você dominar essa habilidade essencial.
          </p>
          
          <p><strong>Inscreva-se agora</strong> e comece sua jornada para se tornar um(a) digitador(a) de alta performance!</p>
        </section>

      </div>

    </div>
  </div>
</div>
</div>
{% include 'footer.html' %}

{% endblock %}