aluno/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.aluno, name='aluno'),
    path('administrador/', views.administrador, name='administrador'),
    path('alunos/', views.lista_alunos, name='aluno_alunos'),
    path('alunos-novo', views.aluno_novo, name='aluno_aluno_novo'),
    path('alunos-update/<int:id>', views.aluno_update, name='aluno_aluno_update'),
    path('alunos-delete/<int:id>', views.aluno_delete, name='aluno_aluno_delete'),
    path('users/<int:user_id>/edit/', views.edit_user, name='edit_user'),
    path('minhaconta/', views.minhaconta, name='minhaconta'),

    path('curso/', views.lista_cursos, name='lista_cursos'),
    path('cursonovo/', views.curso_novo, name='curso_novo'),
    path('curso-update/<int:id>', views.curso_update, name='curso_update'),
    path('curso-delete/<int:id>', views.curso_delete, name='curso_delete'),
    path('curso/<int:id>', views.curso_detalhe, name='curso_detalhe'),
    path('curso/changestatus/<int:id>/<int:categoria_licao>/', views.changeStatus, name='change_status'),
    path('curso/<int:curso_id>/licao/novo/', views.licao_novo, name='licao_novo'),

    path('inscricao/', views.lista_inscricoes, name='lista_inscricoes'),
    path('inscricaolista/', views.lista_inscricao, name='lista_inscricao'),
    path('inscricaonovo/', views.inscricao_novo, name='inscricao_novo'),
    path('inscricao-update/<int:id>', views.inscricao_update, name='inscricao_update'),
    path('inscricao-delete/<int:id>', views.inscricao_delete, name='inscricao_delete'),

    path('licao/<int:id>/', views.lista_Licao, name='lista_licao'),
    path('licao-lista/<int:id>', views.licao_detalhe, name='licao_detalhe'),
    path('licao-update/<int:id>', views.licao_update, name='licao_update'),
    path('licao-delete/<int:id>', views.licao_delete, name='licao_delete'),
    path('download/<int:licao_id>/', views.download_licao, name='download_licao'),

    path('digitacao/', views.lista_digitacao, name='lista_digitacao'),
    path('digitacao-novo/', views.digitacao_novo, name='digitacao_novo'),
    path('digitacao-update/<int:id>', views.digitacao_update, name='digitacao_update'),
    path('digitacao-delete/<int:id>', views.digitacao_delete, name='digitacao_delete'),

    path('inscricao-digitacao/', views.lista_inscricaodigitacao, name='lista_inscricaodigitacao'),
    path('inscricao-digitacao-novo/', views.inscricaodigitacao_novo, name='inscricaodigitacao_novo'),
    path('inscricao-digitacao-update/<int:id>', views.inscricaodigitacao_update, name='inscricaodigitacao_update'),
    path('inscricao-digitacao-delete/<int:id>', views.inscricaodigitacao_delete, name='inscricaodigitacao_delete'),

    path('cursodigitacao/<int:id>', views.cursodigitacao_detalhe, name='cursodigitacao_detalhe'),
    path('cursodigitacao/next/<int:id>', views.cursodigitacao_next, name='cursodigitacao_next'),
    path('cursodigitacao/relatorioDigitacao/', views.relatorioDigitacao, name='relatorioDigitacao'),
    path('cursodigitacao/relatorioDigitacao/relatorio', views.obter_relatorioDigitacao, name='obter_relatorioDigitacao'),
    path('rankindigitacao/', views.rankindigitacao, name='rankindigitacao'),

    path('provasdigitacao/<int:id>', views.provasdigitacao, name='provasdigitacao'),
    path('provasdigitacao/prova/', views.criar_prova_digitacao, name='criar_prova_digitacao'),  
    path('prova/<int:curso_id>/', views.prova, name='prova'),
    path('processar-respostas/<int:curso_id>/', views.processar_respostas, name='processar_respostas'),
    path('resultado-prova/<int:curso_id>/', views.resultado_prova, name='resultado_prova'),
    path('prova/questoes/<int:id>', views.questoes_detalhe, name='questoes_detalhe'),

    path('itens_detalhe/<int:curso_id>/<int:questao_id>', views.itens_detalhe, name='itens_detalhe'),
    path('item/delete/<int:item_id>', views.excluir_item, name='excluir_item'),
    path('item/editar/<int:item_id>', views.editar_item, name='editar_item'),
    path('questao/criar/<int:curso_id>/', views.criar_questao, name='criar_questao'),
    path('questao/editar/<int:questao_id>', views.editar_questao, name='editar_questao'),
    path('questao/delete/<int:questao_id>', views.excluir_questao, name='excluir_questao'),
    
    path('curso/certificado/<int:curso_id>/', views.gerar_certificado, name='gerar_certificado'),
    path('curso/certificado/teste/<int:curso_id>/', views.certificadoteste, name='certificadoteste'),
    path('curso/certificado/gerar_pdf/<int:curso_id>/', views.render_pdf_view, name='render_pdf_view'),
    path('curso/certificado/gerar_pdfDig/', views.render_pdf_digitacao_view, name='render_pdf_digitacao_view'),

    path('marcar-tour-completo/', views.marcar_tour_completo, name='marcar_tour_completo'),
    path('toggle-tour-status/', views.toggle_tour_status, name='toggle_tour_status'),
    path('marcar-tour-completodigi/', views.marcar_tour_completoDig, name='marcar_tour_completoDig'),
    path('toggle-tour-status-dig/', views.toggle_tour_status_dig, name='toggle_tour_status_dig'),
]

infox/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aluno.urls')),
    path('', include('django.contrib.auth.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path("accounts/", include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('pedido/', include('pedido.urls')),
    path('perfil/', include('perfil.urls')),
    
    path('site/', views.site_detalhes, name='site_detalhes'),

    path('infox/<int:id>/', views.infox_detalhes, name='infox_detalhes'),
    path('infoxlista/<int:id>/', views.infox_lista, name='infox_lista'),
    path('infoxnovo/', views.infox_novo, name='infox_novo'),
    path('infoxupdate/<int:id>/', views.infox_update, name='infox_update'),
    path('infoxequinovo/', views.infox_equi_novo, name='infox_equi_novo'),
    path('infoxequilista/', views.infox_equi_lista, name='infox_equi_lista'),
    path('infoxequiupdate/<int:id>/', views.infox_equi_update, name='infox_equi_update'),
    path('infoxequidelete/<int:id>/', views.infox_equi_delete, name='infox_equi_delete'),

    path('contato/', views.contato_detalhes, name='contato_detalhes'),
    path('contatoenviado/', views.contato_enviado, name='contato_enviado'),
    
    path('superior/', views.superior_detalhes, name='superior_detalhes'),
    path('superiorlista/<int:id>/', views.superior_lista, name='superior_lista'),
    path('superiornovo/', views.superior_novo, name='superior_novo'),
    path('superiorupdate/<int:id>/', views.superior_update, name='superior_update'),
    path('superiorlogonovo/', views.superior_logo_novo, name='superior_logo_novo'),
    path('superiorlogolista', views.superior_logo_lista, name='superior_logo_lista'),
    path('superiorlogoupdate/<int:id>/', views.superior_logo_update, name='superior_logo_update'),
    path('superiorlogodelete/<int:id>/', views.superior_logo_delete, name='superior_logo_delete'),
    path('superiorsupernovo/', views.superior_super_novo, name='superior_super_novo'),
    path('superiorsuperlista/', views.superior_super_lista, name='superior_super_lista'),
    path('superiorsuperupdate/<int:id>/', views.superior_super_update, name='superior_super_update'),
    path('superiorsuperdelete/<int:id>/', views.superior_super_delete, name='superior_super_delete'),
    path('superiortecnovo/', views.superior_tec_novo, name='superior_tec_novo'),
    path('superiorteclista/', views.superior_tec_lista, name='superior_tec_lista'),
    path('superiortecupdate/<int:id>/', views.superior_tec_update, name='superior_tec_update'),
    path('superiortecdelete/<int:id>/', views.superior_tec_delete, name='superior_tec_delete'),
    path('superiorposnovo/', views.superior_pos_novo, name='superior_pos_novo'),
    path('superiorposlista/', views.superior_pos_lista, name='superior_pos_lista'),
    path('superiorposupdate/<int:id>/', views.superior_pos_update, name='superior_pos_update'),
    path('superiorposdelete/<int:id>/', views.superior_pos_delete, name='superior_pos_delete'),
    path('superiormbanovo/', views.superior_mba_novo, name='superior_mba_novo'),
    path('superiormbalista/', views.superior_mba_lista, name='superior_mba_lista'),
    path('superiormbaupdate/<int:id>/', views.superior_mba_update, name='superior_mba_update'),
    path('superiormbadelete/<int:id>/', views.superior_mba_delete, name='superior_mba_delete'),

    path('prof/', views.prof_detalhes, name='prof_detalhes'),
    path('profnovo/', views.prof_novo, name='prof_novo'),
    path('proflista/<int:id>/', views.prof_lista, name='prof_lista'),
    path('profupdate/<int:id>/', views.prof_update, name='prof_update'),
    path('proflogonovo/', views.prof_logo_novo, name='prof_logo_novo'),
    path('proflogolista', views.prof_logo_lista, name='prof_logo_lista'),
    path('proflogoupdate/<int:id>/', views.prof_logo_update, name='prof_logo_update'),
    path('proflogodelete/<int:id>/', views.prof_logo_delete, name='prof_logo_delete'),
    path('profpacotenovo/', views.prof_pacote_novo, name='prof_pacote_novo'),
    path('profpacotelista/', views.prof_pacote_lista, name='prof_pacote_lista'),
    path('profpacoteupdate/<int:id>/', views.prof_pacote_update, name='prof_pacote_update'),
    path('profpacotedelete/<int:id>/', views.prof_pacote_delete, name='prof_pacote_delete'),
    path('profcursonovo/', views.prof_curso_novo, name='prof_curso_novo'),
    path('profcursolista/', views.prof_curso_lista, name='prof_curso_lista'),
    path('profcursoupdate/<int:id>/', views.prof_curso_update, name='prof_curso_update'),
    path('profcursodelete/<int:id>/', views.prof_curso_delete, name='prof_curso_delete'),
    path('profturmanovo/', views.prof_turma_novo, name='prof_turma_novo'),
    path('profturmalista/', views.prof_turma_lista, name='prof_turma_lista'),
    path('profturmaupdate/<int:id>/', views.prof_turma_update, name='prof_turma_update'),
    path('profturmadelete/<int:id>/', views.prof_turma_delete, name='prof_turma_delete'),

    path('cursoson/', views.cursoson_detalhes, name='cursoson_detalhes'),
    path('cursosonindiv/<int:id>/', views.cursoson_indivi, name='cursoson_indivi'),
    path('cursosondig/', views.cursoson_dig, name='cursoson_dig'),
    
]

pedido/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pedido'

urlpatterns = [
    path('', views.Pagar, name='pagar'),
    path('carrinho/', views.Carrinho, name='carrinho'),
    path('addcarrinho/<int:id>/', views.AddCarrinho, name='addcarrinho'),
    path('addcarrinhodig/', views.AddCarrinhoDig, name='AddCarrinhoDig'),
    path('removercarrinho/<int:id>/', views.RemoverCarrinho, name='removercarrinho'),
    path('removercarrinhodig/', views.RemoverCarrinhoDig, name='removercarrinhodig'),
    path('continuarcarrinho/<int:id>/', views.ContinuarCarrinho, name='continuarcarrinho'),
    path('continuarcarrinhodig/', views.ContinuarCarrinhoDig, name='continuarcarrinhodig'),
    path('resumo/', views.Resumo, name='resumo'),
    
    #path('fecharpedido/', views.FecharPagar, name='fecharpagar'),
]

perfil/urls.py
from . import views
from django.urls import path
from . import views
from django.conf import settings


app_name = 'perfil'

urlpatterns = [
    path('criar/', views.criar_usuario_view, name='criar'),
]

pedido/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from aluno.models import Aluno



class PerfilForm(ModelForm):
    class Meta:
        model = Aluno
        fields = '__all__'
        exclude = ('user',)

class UserForm(ModelForm):
    class Meta:
        model = User
        fiels = ('first_name', 'last_name', 'username', 'password', 'email')

    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data

pedido/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from aluno.models import Curso as CursoAluno, Curso, DigitacaoDetalhes
from django.contrib import messages


def Pagar(request):
    return render(request, 'pedido/pedido.html')

def adicionar_ao_carrinho(request, id):
    curso = get_object_or_404(Curso, id=id)
    carrinho = request.session.get('carrinho', {})

    if str(id) in carrinho:
        carrinho[str(id)] += 1
    else:
        carrinho[str(id)] = 1

    request.session['carrinho'] = carrinho
    request.session.modified = True

def addcarrinho_dig(request):
    dig = get_object_or_404(DigitacaoDetalhes, nome='Digitação')  
    carrinho = request.session.get('carrinho', {})

    # Use o nome do curso como identificador no carrinho
    dig_key = f'dig-{dig.nome}'

    # Verifica se o curso já foi adicionado ao carrinho
    if dig_key not in carrinho:
        carrinho[dig_key] = 1  # Adiciona ao carrinho com quantidade 1
    
    request.session['carrinho'] = carrinho
    request.session.modified = True

def AddCarrinho(request, id):
    adicionar_ao_carrinho(request, id)
    return redirect('pedido:continuarcarrinho', id=id)

def AddCarrinhoDig(request):
    addcarrinho_dig(request)
    return redirect('pedido:continuarcarrinhodig')


def Carrinho(request):
    carrinho = request.session.get('carrinho', {})

    # IDs numéricos para cursos normais
    curso_ids = [int(k) for k in carrinho.keys() if not k.startswith('dig-')]
    cursos = Curso.objects.filter(id__in=curso_ids)

    # Strings para cursos de digitação
    digitacao_key = [k for k in carrinho.keys() if k.startswith('dig-')]
    digitacao_curso = None
    if digitacao_key:
        nome_curso_dig = digitacao_key[0].split('-')[1]
        digitacao_curso = DigitacaoDetalhes.objects.filter(nome=nome_curso_dig).first()

    # Calcular o total dos valores
    total = sum(curso.preco for curso in cursos)
    if digitacao_curso:
        total += digitacao_curso.valor

    total_itens = sum(carrinho.values())
    

    dados = {
        'cursos': cursos,
        'digitacao_curso': digitacao_curso,
        'carrinho': carrinho,
        'total_itens': total_itens,
        'total': total,
    }
    return render(request, 'pedido.html', dados)



def ContinuarCarrinho(request, id):
    curso = get_object_or_404(Curso, id=id)
    carrinho = request.session.get('carrinho', {})
    
    if str(id) not in carrinho:
        carrinho[str(id)] = 1
        request.session['carrinho'] = carrinho
        request.session.modified = True
        
    cursos = Curso.objects.filter(id__in=[int(k) for k in carrinho.keys() if not k.startswith('dig-')])
    
    dados = {
        'curso': curso,
        'cursos': cursos,
        'carrinho': carrinho,
    }
    return render(request, 'continuarcarrinho.html', dados)


def ContinuarCarrinhoDig(request):
    # Substitua 'Curso de Digitação' pelo nome do curso no banco de dados
    dig = get_object_or_404(DigitacaoDetalhes, nome='Digitação')
    carrinho = request.session.get('carrinho', {})

    dig_key = f'dig-{dig.nome}'

    if dig_key not in carrinho:
        carrinho[dig_key] = 1
        request.session['carrinho'] = carrinho
        request.session.modified = True
    
    dados = {
        'dig': dig,
        'carrinho': carrinho,
    }
    return render(request, 'continuarcarrinhodig.html', dados)

def RemoverCarrinho(request, id):
    carrinho = request.session.get('carrinho', {})
    if str(id) in carrinho:
        del carrinho[str(id)]  # Remove o item do carrinho

    request.session['carrinho'] = carrinho
    return redirect('pedido:carrinho')  # Redireciona de volta para a página do carrinho

def RemoverCarrinhoDig(request):
    carrinho = request.session.get('carrinho', {})
    dig_key = None
    for key in carrinho.keys():
        if key.startswith('dig-'):
            dig_key = key
            break
        
    if dig_key:
        del carrinho[dig_key]  # Remove o curso de digitação do carrinho
    
    request.session['carrinho'] = carrinho
    return redirect('pedido:carrinho')  # Redireciona de volta para a página do carrinho

def Resumo(request):
    carrinho = request.session.get('carrinho', {})

    # Filtrar cursos normais (não digitação)
    cursos = Curso.objects.filter(id__in=[int(k) for k in carrinho.keys() if not k.startswith('dig-')])
    
    # Filtrar curso de digitação
    digitacao_key = [k for k in carrinho.keys() if k.startswith('dig-')]
    
    # Verifica se existe um curso de digitação no carrinho e recupera o primeiro
    digitacao_curso = None
    if digitacao_key:
        nome_curso_dig = digitacao_key[0].split('-')[1]  # Extrai o nome do curso de digitação
        digitacao_curso = DigitacaoDetalhes.objects.filter(nome=nome_curso_dig).first()

    # Calcular o total dos valores
    total = sum(curso.preco for curso in cursos)
    if digitacao_curso:
        total += digitacao_curso.valor

    total_itens = sum(carrinho.values())

    dados = {
        'cursos': cursos,
        'digitacao_curso': digitacao_curso,
        'carrinho': carrinho,
        'total_itens': total_itens,
        'total': total,
    }
    return render(request, 'resumo.html', dados)

pedido/templates/continuarcarrinho.html
{% extends "base_login.html" %}
{% load static %}
{% load custom_filters %}
{% load bootstrap %}
{% load carrinho_extras %}
{% block main %}
</head>
{% include 'nav.html' %}
<div class="gradCapaSuper wow fadeInDown">
    <br><br><br><br><br>
 </div>
 <div class="container">
    <div>
      <br>
      <table class="table table-borderless">
        <thead>
          <tr class="border-0">
            <th scope="col" style="width: 100px;"></th>
            <th scope="col"></th>
          </tr>
        </thead>

        <tbody>
          <tr class="">
            <th scope="row"><img src="{% static curso.imagem %}" alt="Imagem Logo"></th>
            <td class="align-middle">
              <h1 class="text-secondary">{{ curso.nome }}</h1>
              <h5 class="text-secondary">{{ curso.descricao }}</h5>
              <h6></h6>
              <h2><span class="badge text-bg-secondary">R$ {{ curso.preco }}</span></h2>
            </td>
          </tr>
        </tbody>

      </table>
    </div>
    <div class="d-flex justify-content-center" style="margin-top: 10px;">
        <a href="{% url 'cursoson_detalhes' %}">
            <button type="button" class="btn btn btn-light text-primary" style="height: 45px; margin-right: 10px; border-color: rgb(1, 126, 209);">
                <p>CONTINUAR COMPRANDO </p>
            </button>
        </a>
        <a href="{% url 'pedido:carrinho' %}">
            <button type="button" class="btn btn-primary" style="height: 45px;">
                <p><i class="fa-solid fa-cart-shopping"></i> IR PARA O CARRINHO</p>
            </button>
        </a>
    </div>
    <br>
</div>

{% include 'footer.html' %}

{% endblock %}

pedido/templates/continuarcarrinhodig.html
{% extends "base_login.html" %}
{% load static %}
{% load custom_filters %}
{% load bootstrap %}
{% load carrinho_extras %}
{% block main %}
</head>
{% include 'nav.html' %}
<div class="gradCapaSuper wow fadeInDown">
    <br><br><br><br><br>
 </div>
 <div class="container">
    <div>
      <br>
      <table class="table table-borderless">
        <thead>
          <tr class="border-0">
            <th scope="col" style="width: 100px;"></th>
            <th scope="col"></th>
          </tr>
        </thead>

        <tbody>
          <tr class="">
            <th scope="row"><img src="{% static 'media/curso/capa/digitacao.png' %}" alt="Imagem Logo"></th>
            <td class="align-middle">
              <h1 class="text-secondary">{{ dig.nome }}</h1>
              <h5 class="text-secondary">{{ dig.descricao }}</h5>

              <h2><span class="badge text-bg-secondary">R$ {{ dig.valor }}</span></h2>
            </td>
          </tr>
        </tbody>

      </table>
    </div>
    <div class="d-flex justify-content-center" style="margin-top: 10px;">
        <a href="{% url 'cursoson_detalhes' %}">
            <button type="button" class="btn btn btn-light text-primary" style="height: 45px; margin-right: 10px; border-color: rgb(1, 126, 209);">
              <p>CONTINUAR COMPRANDO </p>
            </button>
        </a>
        <a href="{% url 'pedido:carrinho' %}">
            <button type="button" class="btn btn-primary" style="height: 45px;">
              <p><i class="fa-solid fa-cart-shopping"></i> IR PARA O CARRINHO</p>
            </button>
        </a>
    </div>
    <br>
</div>

{% include 'footer.html' %}

{% endblock %}

pedido/templates/pedido.html
{% extends "base_login.html" %}
{% load static %}
{% block main %}
{% load custom_filters %}
{% load bootstrap %}
{% load carrinho_extras %}

</head>
  

{% include 'nav.html' %}

<style>
  .progress-container {
    display: flex;
    align-items: center;
    justify-content: flex-end; /* Alinha os elementos internos à direita */
    width: auto;
    max-width: 400px;
    margin: 0 auto;
    margin-bottom: 50px;
  }

  .step {
      text-align: center;
      position: relative;
      flex: 1;
  }

  .step:not(:last-child)::after {
      content: '';
      position: absolute;
      top: 30%;
      left: 50%;
      transform: translateY(-100%);
      height: 4px;
      width: 100%;
      background-color: #94a8bd;
      z-index: -1;
  }

  .circle {
      width: 40px;
      height: 40px;
      border-radius: 50%;
      background-color: #94a8bd;
      color: white;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 20px;
      margin: 0 auto 10px;
      position: relative;
      z-index: 1;
  }

  .step.active .circle {
    width: 40px;
    height: 40px;
    background-color: #28a745;
  }

  .label {
      font-size: 14px;
      margin-top: 10px;
      color: #5e758f;
  }

  .step.active.step:not(:last-child)::after  {
    background-color: #28a745;
  }
</style>

<div class="gradCapaSuper wow fadeInDown">
   <br><br><br><br><br>
</div>
{% if cursos or digitacao_curso %}
    <div class="container">
      <h1 class="text-secondary" style="text-align: center;">Seu Carrinho</h1>
      <div style="text-align: right;">
      <div class="progress-container">
        <div class="step active">
            <div class="circle">1</div>
            <div class="label">Carrinho</div>
        </div>
        <div class="step">
            <div class="circle">2</div>
            <div class="label">Identificação</div>
        </div>
        <div class="step">
            <div class="circle">3</div>
            <div class="label">Pagamento</div>
        </div>
        <div class="step">
            <div class="circle">4</div>
            <div class="label">Finalização</div>
        </div>
    </div>
  </div>
    <div>
      
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th scope="col" class="text-center align-middle" style="width: 100px;">Curso</th>
            <th scope="col">Descrição</th>
            <th scope="col" class="text-center align-middle" style="width: 100px;">Quantidade</th>
            <th scope="col" class="text-center align-middle" style="width: 100px;">Valor</th>
            <th scope="col" style="width: 70px;">Remover</th>
          </tr>
        </thead>
        <tbody>
          {% for curso in cursos %}
          <tr class="">
            <th scope="row" style="padding: 0px;"><img src="{% static curso.imagem %}" alt="Imagem Logo"></th>
            <td class="align-middle"><a href="{% url 'cursoson_indivi' curso.id %}">{{ curso.nome }}</a></td>
            <td class="text-center align-middle">1</td>
            <td class="text-center align-middle">{{ curso.preco }}</td>
            <td class="text-center align-middle">
              <a href="{% url 'pedido:removercarrinho' curso.id %}">
                <i class="fa-solid fa-trash"  style="color: rgb(177, 16, 16);"></i>
              </a>
          </td>
          </tr>
          {% endfor %}
          {% if digitacao_curso %}
          <tr class="">
              <th scope="row" style="padding: 0px;">
                  <img src="{% static 'media/curso/capa/digitacao.png' %}" alt="Imagem digitação">
              </th>
              <td class="align-middle"><a href="{% url 'cursoson_dig' %}">{{ digitacao_curso.nome }}</a></td>
              <td class="text-center align-middle">1</td>
              <td class="text-center align-middle">{{ digitacao_curso.valor }}</td>
              <td class="text-center align-middle">
                <a href="{% url 'pedido:removercarrinhodig' %}">
                      <i class="fa-solid fa-trash" style="color: rgb(177, 16, 16);"></i>
                  </a>
              </td>
          </tr>
          {% endif %}


        </tbody>

      </table>
    </div>
    <div class="row">
      <div class="col" style="text-align: right;">
        <table class="table table-striped table-bordered" style="width: 200px; margin-left: auto;">
          <thead>
            <tr>
              <th scope="col" class="text-center">Itens do carrinho</th>
              <th scope="col" style="background-color: #afb1b3;" class="text-center">{{ total_itens }}</th>
            </tr>
          </thead>
        </table>
      </div>
      <div class="col" style="text-align: right;">
        <table class="table table-striped table-bordered" style="width: 200px; margin-left: auto;">
          <thead>
            <tr>
              <th scope="col" style="background-color: #888b8d;" class="text-center">Total</th>
              <th scope="col" class="text-center">{{total}}</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
    
    
    <div style="text-align: right;">
      {% if user.is_authenticated %}
        <a href="{% url 'pedido:resumo' %}">
          <button type="button" class="btn btn-success" style="background-color: #28a745; border: none; width: 200px;">
            Comprar <i class="fa-solid fa-angles-right"></i>
          </button>
        </a>
      {% else %}
        <a href="{% url 'perfil:criar' %}">
          <button type="button" class="btn btn-success" style="background-color: #28a745; border: none; width: 200px;">
            Comprar <i class="fa-solid fa-angles-right"></i>
          </button>
        </a>
      {% endif %}
    </div>
      <br>
  </div>
  {% else %}
  <h4 class="text-center text-secondary" style="margin: 60px;"><i class="fa-solid fa-basket-shopping"></i>Seu carrinho está vazio.</h4>
  {% endif %}
</div>

{% include 'footer.html' %}

{% endblock %}